// Comprehensive Services Directory Data for New Guide Documents Clearing Services Co.
// Strictly adheres to official brand colors (Midnight Navy, Deep Navy, Royal Blue, Electric Cyan, Bright Blue, Ice Blue, Very Light Blue)
// ABSOLUTELY NO GOLD ALLOWED ANYWHERE.

export const INTENT_OPTIONS = [
  {
    id: 'start-business',
    num: '01',
    title: 'START A BUSINESS',
    description: 'Mainland LLCs, Free Zone entities, trade names, initial approvals & licensing.',
    targetServiceId: 'company-formation',
    ctaText: 'EXPLORE BUSINESS SETUP',
  },
  {
    id: 'clear-document',
    num: '02',
    title: 'CLEAR A DOCUMENT',
    description: 'Federal approvals, ministry clearances, physical document processing & filings.',
    targetServiceId: 'documents-clearing',
    ctaText: 'EXPLORE DOCUMENTS CLEARING',
  },
  {
    id: 'get-visa',
    num: '03',
    title: 'GET A VISA',
    description: 'Employment, investor, and partner visas across GDRFA and Ministry of Labor.',
    targetServiceId: 'visa-immigration-ministry-of-labor',
    ctaText: 'EXPLORE VISA SERVICES',
  },
  {
    id: 'attest-document',
    num: '04',
    title: 'ATTEST A DOCUMENT',
    description: 'Government transactions, official attestations, certificates & embassy clearances.',
    targetServiceId: 'government-transactions',
    ctaText: 'EXPLORE ATTESTATION',
  },
  {
    id: 'deal-authority',
    num: '05',
    title: 'DEAL WITH A GOVERNMENT AUTHORITY',
    description: 'Direct liaison across DET, MOHRE, Dubai Municipality, Dubai Courts & federal ministries.',
    targetServiceId: 'government-approval',
    ctaText: 'EXPLORE GOVERNMENT APPROVAL',
  },
  {
    id: 'create-poa',
    num: '06',
    title: 'AUTHORISE SOMEONE / CREATE A POA',
    description: 'Digital Power of Attorney drafting, Dubai Courts notary coordination & legal translation.',
    targetServiceId: 'online-poa',
    ctaText: 'EXPLORE ONLINE POA',
  },
  {
    id: 'renew-licence',
    num: '07',
    title: 'RENEW OR AMEND A BUSINESS LICENCE',
    description: 'Trade licence renewals, Ejari tenancy updates, partner amendments & commercial upkeep.',
    targetServiceId: 'trade-licences-renewal',
    ctaText: 'EXPLORE LICENCE RENEWALS',
  },
  {
    id: 'not-sure',
    num: '08',
    title: "I'M NOT SURE",
    description: 'Tell us your ultimate objective and our clearance directors will chart the exact legal route.',
    targetServiceId: 'consultation',
    ctaText: 'LET US GUIDE YOU →',
  },
];

// APPROVED MAIN SERVICES — EXACT 17 SERVICES IN EXACT ORDER
export const DIRECTORY_SERVICES = [
  {
    num: '01',
    id: 'government-transactions',
    title: 'Government Transactions',
    headline: 'GOVERNMENT\nTRANSACTIONS',
    description:
      'Authorized representative liaison and clearing across UAE ministries and government departments for efficient, accurate submissions and zero-rejection federal approvals.',
    context: 'Broad UAE government liaison & ministerial clearance',
    authority: 'FEDERAL MINISTRIES & AUTHORITIES',
    authorityFull: 'Ministry of Foreign Affairs (MOFA), Ministry of Economy & Federal Agencies',
    jurisdiction: 'ALL 7 EMIRATES // FEDERAL & LOCAL',
    categoryType: 'GOVERNMENT LIAISON & CLEARANCE',
    turnaround: 'Same-Day / 24–48 Hours',
    procedures: [
      'MOFA Document Legalisation & Consular Validation',
      'Federal Ministry Formal Submissions & Inquiries',
      'Inter-Agency Statutory Clearances & Approvals',
      'Official Regulatory Representation & Courier Dispatch',
      'Government Transaction Exception Handling & Petitions',
    ],
    requiredDocuments: [
      'Original Documents requiring attestation or clearance',
      'Valid Emirates ID or Passport Copies of Authorised Signatories',
      'Power of Attorney or Corporate Authorization Letter',
      'Supporting commercial registry or judicial dossiers (if applicable)',
    ],
    faqs: [
      {
        q: 'How fast can MOFA and federal transactions be processed?',
        a: 'Standard electronic attestations are typically completed within 24 to 48 hours. Fast-track physical submissions handled by our in-house PROs can be finalized on the same business day.',
      },
      {
        q: 'Do I need to visit government departments in person?',
        a: 'No. As an authorized corporate liaison, New Guide handles all physical representations, queues, and document handovers on your behalf.',
      },
    ],
    primaryCta: 'EXPLORE GOVERNMENT TRANSACTIONS',
    visualType: 'governmental',
    image: '/service/1.png',
    statLabel: 'FEDERAL CLEARANCES',
    statValue: '100% AUTHORIZED',
  },
  {
    num: '02',
    id: 'dubai-municipality',
    title: 'Dubai Municipality',
    headline: 'DUBAI\nMUNICIPALITY',
    description:
      'Comprehensive clearance and coordination for Dubai Municipality municipal permits, architectural layout approvals, public health compliance, and engineering site endorsements.',
    context: 'Dubai urban planning, built environment & municipal infrastructure',
    authority: 'DUBAI MUNICIPALITY (DM)',
    authorityFull: 'Dubai Municipality — Planning, Health & Environment Sectors',
    jurisdiction: 'EMIRATE OF DUBAI',
    categoryType: 'MUNICIPAL INFRASTRUCTURE & PERMITS',
    turnaround: '24–72 Hours Depending on Category',
    procedures: [
      'Architectural Layout & Spatial Approvals',
      'Food Safety & Foodwatch Regulatory Registrations',
      'Public Health, Clinic & Salon Compliance Permits',
      'Commercial Fit-Out & Engineering Plan Endorsements',
      'Environmental Impact & Waste Classification Approvals',
    ],
    requiredDocuments: [
      'Premises Architectural Layout / Fit-Out Drawing CAD Files',
      'Valid Tenancy Contract & Ejari Certificate',
      'Trade License Copy or Initial Approval Certificate',
      'Contractor / Consultant License and Credentials',
    ],
    faqs: [
      {
        q: 'Which businesses require mandatory Dubai Municipality approval?',
        a: 'All food and beverage establishments, retail fit-outs, beauty salons, healthcare facilities, warehouses, and industrial units must secure DM layout and health clearances before trading.',
      },
      {
        q: 'Can New Guide expedite DM site inspection bookings?',
        a: 'Yes. Our municipal liaison team coordinates directly with DM inspectors to expedite scheduling and ensure complete adherence to technical guidelines prior to visit.',
      },
    ],
    primaryCta: 'EXPLORE DUBAI MUNICIPALITY',
    visualType: 'municipal',
    image: '/service/2.png',
    statLabel: 'MUNICIPAL CODES',
    statValue: 'DM COMPLIANT',
  },
  {
    num: '03',
    id: 'dubai-economy-development',
    title: 'Dubai Economy Development',
    headline: 'DUBAI ECONOMY\nDEVELOPMENT',
    description:
      'Support for commercial licensing, economic activity classification, initial approvals, and statutory corporate registrations in Dubai’s premier business ecosystem.',
    context: 'Modern Dubai commercial district, commerce, licensing & economic activity',
    authority: 'DET (DUBAI ECONOMY & TOURISM)',
    authorityFull: 'Department of Economy and Tourism — Commercial Licensing Division',
    jurisdiction: 'DUBAI MAINLAND',
    categoryType: 'COMMERCIAL LICENSING & REGISTRATION',
    turnaround: '1–3 Business Days',
    procedures: [
      'Commercial & Professional Licence Issuance',
      'Statutory Trade Name Reservation & Linguistic Verification',
      'Economic Activity Classifications & Activity Codes',
      'Initial Approvals Prior to Commercial Lease Execution',
      'Commercial Registry Entries & Gazette Filings',
    ],
    requiredDocuments: [
      'Passport copies & visa/Emirates ID of all founding partners',
      'Proposed trade names (English & Arabic phonetic transliteration)',
      'Selected commercial activity list from DET official catalog',
      'Tenancy contract (Ejari) for office or commercial space',
    ],
    faqs: [
      {
        q: 'What is the difference between Commercial and Professional licenses in DET?',
        a: 'Commercial licenses govern trading, retail, and general import/export activities, while Professional licenses apply to specialized services, consultancies, and intellectual services.',
      },
      {
        q: 'Can foreigners own 100% of a mainland company in Dubai?',
        a: 'Yes. Following UAE Commercial Companies Law reforms, foreign investors can own 100% of mainland LLCs across more than 2,000 commercial and industrial activities.',
      },
    ],
    primaryCta: 'EXPLORE DUBAI ECONOMY DEVELOPMENT',
    visualType: 'economy-dev',
    image: '/service/3.png',
    statLabel: 'COMMERCIAL LICENSING',
    statValue: 'DIRECT DET LIAISON',
  },
  {
    num: '04',
    id: 'online-poa',
    title: 'Online POA',
    headline: 'ONLINE\nPOA',
    description:
      'Modern digital Power of Attorney drafting, remote Dubai Courts notary execution, and legal Arabic translation for corporate representation, banking proxies, and real estate mandates.',
    context: 'Modern digital legal process & remote notary execution',
    authority: 'DUBAI COURTS NOTARY PUBLIC',
    authorityFull: 'Dubai Courts Notary Public & Remote Judicial Execution Portal',
    jurisdiction: 'REMOTE DIGITAL // DUBAI & UAE COURTS',
    categoryType: 'DIGITAL NOTARIAL INSTRUMENT',
    turnaround: 'Same-Day Digital Verification',
    procedures: [
      'Commercial & General Corporate POA Drafting',
      'Remote Digital Notarization via Video Verification',
      'Special Real Estate, Vehicle & Banking Mandates',
      'Dual-Language Arabic & English Statutory Translation',
      'MOFA Legalisation for Cross-Border Recognition',
    ],
    requiredDocuments: [
      'Emirates ID or Passport Copy of the Principal (Grantor)',
      'Passport / Emirates ID details of the Attorney (Agent)',
      'Title Deed / Trade License copies (if granting property or business powers)',
      'UAE Pass biometric authentication credentials',
    ],
    faqs: [
      {
        q: 'Can I notarize a UAE POA if I am currently outside the UAE?',
        a: 'Yes. Through Dubai Courts digital video notarization and authorized international attestation chains, we facilitate fully remote POA issuance from anywhere in the world.',
      },
      {
        q: 'Is bilingual Arabic-English translation mandatory for UAE POAs?',
        a: 'Yes. UAE statutory courts require all executed powers of attorney to feature sworn Ministry of Justice certified Arabic text alongside English.',
      },
    ],
    primaryCta: 'EXPLORE ONLINE POA',
    visualType: 'online-poa',
    image: '/service/4.png',
    statLabel: 'REMOTE NOTARIZATION',
    statValue: 'DUBAI COURTS DIGITAL',
  },
  {
    num: '05',
    id: 'moa',
    title: 'MOA',
    headline: 'MEMORANDUM OF\nASSOCIATION (MOA)',
    description:
      'Drafting, restructuring, and legally notarizing Memorandums of Association, Articles of Association, and shareholder resolutions for mainland LLCs, free zone entities, and civil partnerships.',
    context: 'Corporate & legal identity formulation without clichés',
    authority: 'MINISTRY OF JUSTICE & DET NOTARY',
    authorityFull: 'Notary Public, Ministry of Justice & Department of Economy and Tourism',
    jurisdiction: 'UAE CORPORATE STATUTE',
    categoryType: 'CORPORATE CONSTITUTIONAL INSTRUMENTS',
    turnaround: '24–48 Hours',
    procedures: [
      'Standard & Custom MOA Bilingual Drafting',
      'MOA Addendums for Share Capital & Ownership Transfers',
      'Director & General Manager Authority Delegation Clauses',
      'Dubai Courts Electronic Notary MOA Attestation',
      'Articles of Association Restructuring & Statutory Compliance',
    ],
    requiredDocuments: [
      'Existing Trade License & Initial Approval Certificate',
      'Passport copies & Emirates IDs of all current and new partners',
      'Proposed shareholding ratios and capital allocation breakdown',
      'Board Resolution authorizing MOA amendment (for corporate shareholders)',
    ],
    faqs: [
      {
        q: 'When is an MOA amendment legally required?',
        a: 'An MOA amendment is required whenever there is a change in company partners, share capital, corporate name, legal structure, manager powers, or business activities.',
      },
      {
        q: 'Can all partners sign the MOA digitally?',
        a: 'Yes. Dubai Courts and DET provide verified digital notarization through UAE Pass, eliminating the need for physical appearances in court.',
      },
    ],
    primaryCta: 'EXPLORE MOA',
    visualType: 'moa',
    image: '/service/5.png',
    statLabel: 'CORPORATE CONSTITUTION',
    statValue: 'NOTARY VALIDATED',
  },
  {
    num: '06',
    id: 'typing',
    title: 'Typing',
    headline: 'PROFESSIONAL\nTYPING',
    description:
      'Precision administrative document compilation, statutory electronic application typing, ministerial portal collation, and format standardization across all UAE digital clearing interfaces.',
    context: 'Close-up professional workstation & precision document compilation',
    authority: 'AUTHORIZED GOV TYPING PORTALS',
    authorityFull: 'Accredited Ministerial Typing Gateways (ICP, GDRFA, MOHRE, MOJ)',
    jurisdiction: 'NATIONWIDE UAE',
    categoryType: 'ADMINISTRATIVE ACCELERATION & TYPING',
    turnaround: 'Immediate / Expedited Digital Delivery',
    procedures: [
      'Federal & Local Government Digital Typing Portals',
      'MOHRE Labour Offer Letters & Contract Typing',
      'Immigration & Residence Application Compilation',
      'Emirates ID Biometric Appointment Typing',
      'Judicial & Notary Submission Form Generation',
    ],
    requiredDocuments: [
      'Applicant Passport Copy and Unified Number (UID)',
      'Sponsor / Company Establishment Card Copy',
      'Previous Visa or Entry Permit details (if renewal or modification)',
      'Personal Photographs matching UAE government biometric specs',
    ],
    faqs: [
      {
        q: 'Why should I use professional typing instead of self-submission?',
        a: 'Typing errors or misclassified activity codes can cause immediate application rejection and statutory fees forfeiture. Our team ensures zero-defect submissions with 100% compliance.',
      },
      {
        q: 'Can you type urgent applications after standard government working hours?',
        a: 'Yes. Our digital typing infrastructure operates extended dispatch hours to prepare filings for immediate early-morning batch submission.',
      },
    ],
    primaryCta: 'EXPLORE TYPING',
    visualType: 'typing',
    image: '/service/6.png',
    statLabel: 'ACCURACY BENCHMARK',
    statValue: 'ZERO-ERROR PROTOCOL',
  },
  {
    num: '07',
    id: 'company-formation',
    title: 'Company Formation',
    headline: 'COMPANY\nFORMATION',
    description:
      'Aspirational corporate structuring and business formation across Dubai mainland and all 40+ UAE free zones, from commercial feasibility and trade name reservation to final license packet delivery.',
    context: 'Dubai business districts, office towers & commercial enterprise inception',
    authority: 'DET & ALL 40+ UAE FREE ZONES',
    authorityFull: 'Department of Economy & Tourism, DMCC, IFZA, DAFZA, Meydan, RAKEZ',
    jurisdiction: 'MAINLAND & FREE ZONE JURISDICTIONS',
    categoryType: 'CORPORATE INCEPTION & STRUCTURING',
    turnaround: '3–5 Business Days',
    procedures: [
      '100% Foreign Ownership Mainland LLC Formations',
      'Free Zone Business Setup (DMCC, IFZA, DAFZA, Meydan, RAKEZ)',
      'Sole Establishments & Civil Professional Partnerships',
      'Corporate Bank Account Introduction Support',
      'Commercial Lease (Ejari) & Physical Office Registration',
    ],
    requiredDocuments: [
      'Passport copies of shareholders and proposed managers',
      'Entry stamp or UAE residence visa copy with Emirates ID (if applicable)',
      '3 Proposed company names in order of preference',
      'Brief summary of commercial business model and target activities',
    ],
    faqs: [
      {
        q: 'Should I set up on Mainland or in a Free Zone?',
        a: 'Mainland entities allow unrestricted trading throughout the entire UAE domestic market and direct governmental tenders. Free Zones offer specific tax efficiencies, customs benefits, and flexible physical office packages.',
      },
      {
        q: 'What is included in the company formation package?',
        a: 'Our packages include trade name reservation, initial approval, MOA formulation, commercial license issuance, corporate tax registration, establishment cards, and banking assistance.',
      },
    ],
    primaryCta: 'EXPLORE COMPANY FORMATION',
    visualType: 'formation',
    image: '/service/7.png',
    statLabel: 'NEW JURISDICTIONS',
    statValue: '40+ FREE ZONES & MAINLAND',
  },
  {
    num: '08',
    id: 'trade-licences-renewal',
    title: 'Trade licences renewal',
    headline: 'TRADE LICENCES\nRENEWAL',
    description:
      'Ensuring unbroken commercial continuity. Accelerated commercial license renewals, Ejari verification, regulatory penalty mitigation, and activity upkeep before statutory expirations.',
    context: 'Commercial continuity & proactive cyclical renewals',
    authority: 'DET & FREE ZONE REGISTRIES',
    authorityFull: 'Department of Economy and Tourism (DET) & Respective Free Zone Authorities',
    jurisdiction: 'DUBAI & NORTHERN EMIRATES',
    categoryType: 'COMMERCIAL CONTINUITY & COMPLIANCE',
    turnaround: '24–48 Hours',
    procedures: [
      'Fast-Track Commercial License Renewal Processing',
      'Commercial Tenancy Contract (Ejari) Audit & Upload',
      'Overdue Fine Mitigation & Grace Period Management',
      'Chamber of Commerce Membership Annual Upkeep',
      'Automated Multi-Year License Expiry Monitoring',
    ],
    requiredDocuments: [
      'Current Trade License copy',
      'Valid Tenancy Contract & Ejari registration certificate',
      'Passport & Emirates ID copies of partners/manager',
      'External Department No Objection Certificates (if activity requires annual renewal)',
    ],
    faqs: [
      {
        q: 'What penalties apply if a license expires without renewal?',
        a: 'DET charges a monthly fine starting from AED 250 to AED 500+, and operating on an expired license can freeze corporate bank accounts, employee visas, and customs codes.',
      },
      {
        q: 'Can New Guide renew my license if my commercial lease is not yet updated?',
        a: 'We can facilitate interim auto-renewals or temporary permits in accordance with DET regulations while commercial lease formalization is underway.',
      },
    ],
    primaryCta: 'EXPLORE TRADE LICENCES RENEWAL',
    visualType: 'renewal',
    image: '/service/8.png',
    statLabel: 'BUSINESS CONTINUITY',
    statValue: 'UNINTERRUPTED TRADING',
  },
  {
    num: '09',
    id: 'documents-clearing',
    title: 'Documents Clearing',
    headline: 'DOCUMENTS\nCLEARING',
    description:
      'The core operational specialty of New Guide. Structured administrative clearing of corporate, commercial, legal, and educational files through UAE governmental hierarchies.',
    context: 'Physical document-processing environment, organised files & controlled clearing',
    authority: 'INTER-AGENCY CLEARANCE HUB',
    authorityFull: 'Multi-Departmental UAE Government Clearance Liaison',
    jurisdiction: 'UAE NATIONWIDE // ALL 7 EMIRATES',
    categoryType: 'STATUTORY DOCUMENT EXPEDITION & PROTOCOL',
    turnaround: 'Same-Day / 24 Hours',
    procedures: [
      'Physical & Electronic Ministry Document Clearance',
      'Chamber of Commerce Invoices & Certificates of Origin',
      'Embassy & Consular Dossier Processing',
      'Regulatory Rejection Remediation & Resubmission',
      'Dedicated Secure Courier & Chain-of-Custody Dispatch',
    ],
    requiredDocuments: [
      'Original documents requiring clearance or attestation',
      'Identification of authorizing corporate officer',
      'Specific ministry submission requisition or case number',
      'Supporting commercial invoices or board declarations (where relevant)',
    ],
    faqs: [
      {
        q: 'What makes New Guide’s document clearing distinct?',
        a: 'We do not operate as generic messengers. Our seasoned PROs understand exact ministerial submission requirements, preventing common formatting rejections and safeguarding deadlines.',
      },
      {
        q: 'Do you provide end-to-end doorstep collection and delivery in Dubai?',
        a: 'Yes. We offer secure chain-of-custody pickup from your corporate offices or residence across Dubai, followed by verified hand-delivery post-approval.',
      },
    ],
    primaryCta: 'EXPLORE DOCUMENTS CLEARING',
    visualType: 'doc-clearing',
    image: '/service/9.png',
    statLabel: 'CORE SPECIALTY',
    statValue: 'VERIFIED DISPATCH',
  },
  {
    num: '10',
    id: 'amer-tasheel-tadbeer',
    title: 'Amer, Tasheel, tadbeer',
    headline: 'AMER, TASHEEL,\nTADBEER',
    description:
      'Seamless multi-channel governmental liaison across the three core UAE citizen and corporate processing pillars: Amer for GDRFA immigration, Tasheel for MOHRE labour, and Tadbeer for domestic workers.',
    context: 'Tri-channel government pathways converging smoothly',
    authority: 'GDRFA, MOHRE & TADBEER REGISTRIES',
    authorityFull: 'Amer Centres (GDRFA), Tasheel Service Centres (MOHRE) & Tadbeer Centres',
    jurisdiction: 'DUBAI & UAE RESIDENCY',
    categoryType: 'TRI-CHANNEL GOVERNMENT PILLARS',
    turnaround: '24–48 Hours',
    procedures: [
      'Amer Centre Entry Permits & Dubai Residency Filings',
      'Tasheel Labour Quotas, Work Permits & Establishment Cards',
      'Tadbeer Domestic Worker Sponsorship & Visa Packages',
      'Status Adjustment & In-Country Visa Amendments',
      'Labour Contract Registration & Wage Protection (WPS)',
    ],
    requiredDocuments: [
      'Sponsor Trade License / Establishment Card or Personal Emirates ID',
      'Candidate Passport Copy & Unified Number (UID)',
      'Official MOHRE Job Offer Letter or Contract Draft',
      'Attested Educational Degrees (for skilled category positions)',
    ],
    faqs: [
      {
        q: 'What transactions fall under Amer vs Tasheel?',
        a: 'Amer handles Dubai immigration, visa issuance, and residency stamping under GDRFA. Tasheel handles labor cards, employment contracts, quotas, and establishment cards under MOHRE.',
      },
      {
        q: 'How does Tadbeer handle domestic staff visas?',
        a: 'Tadbeer manages legal sponsorship, medicals, insurance, and residency stamping for household staff, drivers, nannies, and domestic workers under Ministry regulations.',
      },
    ],
    primaryCta: 'EXPLORE AMER, TASHEEL, TADBEER',
    visualType: 'tri-channel',
    image: '/service/10.png',
    statLabel: 'PILLARS COVERED',
    statValue: 'AMER + TASHEEL + TADBEER',
  },
  {
    num: '11',
    id: 'visa-immigration-ministry-of-labor',
    title: 'Visa immigration/ Ministry of Labor',
    headline: 'VISA IMMIGRATION/\nMINISTRY OF LABOR',
    description:
      'Strategic corporate workforce compliance and residency management. Bridging GDRFA/ICP immigration channels and the Ministry of Human Resources and Emiratisation (MOHRE).',
    context: 'Residency mobility, professional workforce & immigration trajectory',
    authority: 'GDRFA / ICP / MOHRE',
    authorityFull: 'General Directorate of Residency and Foreigners Affairs & Ministry of Human Resources & Emiratisation',
    jurisdiction: 'FEDERAL UAE',
    categoryType: 'CORPORATE WORKFORCE & IMMIGRATION',
    turnaround: '3–5 Business Days',
    procedures: [
      'Corporate Employee Visa Quota Approvals',
      'Work Permit Issuance, Modification & Cancellation',
      'Professional Residency Entry Permits & Status Amendments',
      'Establishment File Creation & Digital Portal Activation',
      'MOHRE Labour Compliance & Absconding Resolution',
    ],
    requiredDocuments: [
      'Company Establishment Cards (Immigration & Labour)',
      'Employee Passport Copy & High-Resolution Photograph',
      'Attested Degree / Diploma for Skilled Worker Levels 1–3',
      'Signed MOHRE Offer Letter and Standardized Contract',
    ],
    faqs: [
      {
        q: 'What are the skilled worker categories under MOHRE?',
        a: 'MOHRE classifies workers into 5 skill levels, where Levels 1–3 require verified university degrees or professional diplomas for specific designation titles.',
      },
      {
        q: 'How are employee work permit quotas allocated?',
        a: 'Quota limits are determined by commercial office square footage (Ejari registered size), activity type, and your company’s Emiratisation compliance track record.',
      },
    ],
    primaryCta: 'EXPLORE VISA IMMIGRATION / MINISTRY OF LABOR',
    visualType: 'workforce-visa',
    image: '/service/11.png',
    statLabel: 'LABOUR REGISTRY',
    statValue: 'MOHRE COMPLIANT',
  },
  {
    num: '12',
    id: 'visit-visa-family-visa',
    title: 'Visit visa family visa',
    headline: 'VISIT VISA\nFAMILY VISA',
    description:
      'Personal and family sponsorship pathways managed with human care and legal precision. Sponsoring spouses, children, and parents alongside multi-duration visitor entry permits.',
    context: 'Family lifestyle & professional residence in Dubai',
    authority: 'GDRFA DUBAI & ICP FEDERAL',
    authorityFull: 'GDRFA Dubai & Federal Authority for Identity, Citizenship, Customs & Port Security (ICP)',
    jurisdiction: 'FAMILY RESIDENCY & VISITOR ENTRY',
    categoryType: 'PERSONAL & FAMILY SPONSORSHIP',
    turnaround: '24–48 Hours',
    procedures: [
      'Spouse & Children 2-Year Residency Sponsorship',
      'Parents Long-Term Dependent Visa Approvals',
      '30-Day, 60-Day & 90-Day Tourist & Business Visit Visas',
      'In-Country Visit Visa Extensions & Status Changes',
      'Salary Certificate & Tenancy Validation for Sponsoring',
    ],
    requiredDocuments: [
      'Sponsor Emirates ID, Original Passport, and Valid Residence Visa',
      'Registered Ejari Tenancy Contract (minimum 1-bedroom for family)',
      'Attested Marriage Certificate (for spouse) & Attested Birth Certificates (for children)',
      'Official Salary Certificate or Company Shareholder Proof (minimum AED 4,000/month)',
    ],
    faqs: [
      {
        q: 'What is the minimum salary required to sponsor a family in Dubai?',
        a: 'The statutory minimum monthly salary is AED 4,000, or AED 3,000 plus company-provided accommodation. Sponsoring parents typically requires a minimum salary of AED 20,000.',
      },
      {
        q: 'Can visit visa holders convert directly to residency without exiting the country?',
        a: 'Yes. In-country status change permits allow seamless conversion from tourist or visit status to residence visa without border runs.',
      },
    ],
    primaryCta: 'EXPLORE VISIT VISA FAMILY VISA',
    visualType: 'family-visa',
    image: '/service/12.png',
    statLabel: 'FAMILY RESIDENCE',
    statValue: 'DEPENDENT APPROVED',
  },
  {
    num: '13',
    id: 'insurance',
    title: 'Insurance',
    headline: 'CORPORATE &\nRESIDENCY INSURANCE',
    description:
      'Statutory health insurance coverage, mandatory employee basic health plans (DHA compliance), commercial property insurance, and workers compensation protection.',
    context: 'Protection, assurance & corporate risk mitigation',
    authority: 'DUBAI HEALTH AUTHORITY (DHA) & INSURERS',
    authorityFull: 'Dubai Health Authority (DHA) & Accredited UAE Insurance Providers',
    jurisdiction: 'UAE REGULATORY INSURANCE',
    categoryType: 'MANDATORY COMPLIANCE PROTECTION',
    turnaround: 'Same-Day Policy Generation',
    procedures: [
      'DHA Compliant Mandatory Employee Health Insurance',
      'Investor & Partner VIP Private Health Insurance Plans',
      'Family Dependent Essential Benefits Package (EBP)',
      'Workmen Compensation & Commercial Liability Policies',
      'Statutory ILOE (Involuntary Loss of Employment) Support',
    ],
    requiredDocuments: [
      'Trade License & Establishment Card Copy (for corporate policies)',
      'Emirates ID & Passport copy of each insured member',
      'Employee salary band and job designation details',
      'Previous policy claims history (for group transitions)',
    ],
    faqs: [
      {
        q: 'Is health insurance legally mandatory in Dubai?',
        a: 'Yes. Under Dubai Health Insurance Law No. 11 of 2013, all employers must provide compliant health coverage for their employees, and sponsors must insure their dependents.',
      },
      {
        q: 'What happens if employee insurance is not active during visa renewal?',
        a: 'GDRFA residency renewals are blocked if an active DHA-compliant health policy certificate is not linked to the applicant’s Emirates ID.',
      },
    ],
    primaryCta: 'EXPLORE INSURANCE',
    visualType: 'insurance',
    image: '/service/13.png',
    statLabel: 'HEALTH COMPLIANCE',
    statValue: 'DHA ALIGNED',
  },
  {
    num: '14',
    id: 'government-approval',
    title: 'Government Approval',
    headline: 'GOVERNMENT\nAPPROVAL',
    description:
      'External departmental approvals and ministerial No Objection Certificates (NOCs) required across specialized sectors before trade licenses can be activated or facilities opened.',
    context: 'Progress toward completion & procedural clearance language',
    authority: 'EXTERNAL REGULATORY AUTHORITIES',
    authorityFull: 'Civil Defense, RTA, SIRA, TDRA, KHDA, Ministry of Climate Change',
    jurisdiction: 'SECTOR-SPECIFIC UAE BODIES',
    categoryType: 'STATUTORY NOC & SPECIAL PERMITS',
    turnaround: '2–5 Business Days',
    procedures: [
      'Civil Defense (DCD) Safety Approvals & Inspections',
      'Roads & Transport Authority (RTA) Commercial Approvals',
      'Telecommunications and Digital Government (TDRA) Permits',
      'Security Industry Regulatory Agency (SIRA) Clearances',
      'Knowledge and Human Development Authority (KHDA) Filings',
    ],
    requiredDocuments: [
      'Initial Approval Certificate from licensing authority (DET / Free Zone)',
      'Technical premises drawings & civil engineering specifications',
      'Management professional qualifications and police clearance certificates',
      'Security / safety device inventory and installation compliance receipts',
    ],
    faqs: [
      {
        q: 'Why do certain trade activities need external government approvals?',
        a: 'Regulated activities such as security, education, healthcare, transport, and telecommunications require specialized regulatory oversight to protect public welfare and statutory standards.',
      },
      {
        q: 'How does New Guide facilitate multi-agency approvals?',
        a: 'Our liaison officers review your commercial scope, prepare agency-specific compliance dossiers, and submit files simultaneously across relevant ministries.',
      },
    ],
    primaryCta: 'EXPLORE GOVERNMENT APPROVAL',
    visualType: 'approval',
    image: '/service/14.png',
    statLabel: 'EXTERNAL NOCS',
    statValue: 'MINISTERIAL APPROVAL',
  },
  {
    num: '15',
    id: 'dubai-economic-department',
    title: 'Dubai Economic Department',
    headline: 'DUBAI ECONOMIC\nDEPARTMENT',
    description:
      'Dedicated institutional liaison for Department of Economy and Tourism commercial registers, trade name renewals, manager appointments, share transfers, and gazette amendments.',
    context: 'Dubai commercial registry environment & mainland institutional structure',
    authority: 'DED / DET COMMERCIAL REGISTER',
    authorityFull: 'Dubai Economic Department (DED) / Department of Economy and Tourism (DET)',
    jurisdiction: 'MAINLAND DUBAI',
    categoryType: 'STATUTORY COMMERCIAL JURISDICTION',
    turnaround: '24–48 Hours',
    procedures: [
      'DED Commercial Register Extracts & Certificates',
      'Share Transfer & Partner Substitution Filings',
      'Manager Appointment, Change & Revocation Clearances',
      'Branch Office Registration for Foreign & Freezone Companies',
      'Commercial Activity Additions & Deletions',
    ],
    requiredDocuments: [
      'Current Commercial Registration & License copy',
      'Notarized Share Purchase Agreement or Board Resolution',
      'Updated Memorandum of Association (MOA) Addendum',
      'Emirates ID / Passport of newly appointed directors or partners',
    ],
    faqs: [
      {
        q: 'What is a Commercial Register extract from DED?',
        a: 'An official certificate issued by the economic department confirming corporate ownership, legal form, capital, manager powers, and active commercial status.',
      },
      {
        q: 'Can a free zone company open a mainland branch through DED?',
        a: 'Yes. Free zone entities and foreign multinational corporations can establish official mainland branches through the Department of Economy and Tourism.',
      },
    ],
    primaryCta: 'EXPLORE DUBAI ECONOMIC DEPARTMENT',
    visualType: 'ded',
    image: '/service/15.png',
    statLabel: 'COMMERCIAL REGISTER',
    statValue: 'DED MAINLAND',
  },
  {
    num: '16',
    id: 'notary-services',
    title: 'Notary Services',
    headline: 'NOTARY\nSERVICES',
    description:
      'Formal liaison with Dubai Courts Notary Public for judicial attestation of contracts, commercial agreements, board resolutions, settlements, and legal statutory declarations.',
    context: 'Formal legal setting, judicial architecture & notarial seal',
    authority: 'DUBAI COURTS NOTARY PUBLIC',
    authorityFull: 'Dubai Courts Notary Public Divisions (Al Barsha, Al Twar, Wafi, Online)',
    jurisdiction: 'JUDICIAL LEGAL SETTING // DUBAI COURTS',
    categoryType: 'JUDICIAL NOTARIAL AUTHENTICATION',
    turnaround: 'Same-Day Attestation',
    procedures: [
      'Judicial Commercial Contracts Notarization',
      'Share Purchase Agreement Notary Execution',
      'Legal Notice Drafting & Judicial Delivery Coordination',
      'Sworn Declarations & Corporate Undertakings Attestation',
      'Certified Legal Translations Attested at Notary Public',
    ],
    requiredDocuments: [
      'Original identification (Emirates ID / Passport) of all signatories',
      'Original draft agreement in verified dual-column Arabic & English format',
      'Company trade license and existing constitutional documents',
      'Judicial proxy or board authorization (if signing on behalf of a company)',
    ],
    faqs: [
      {
        q: 'Why must contracts be notarized by Dubai Courts?',
        a: 'Notarization provides legal enforceability before UAE civil and commercial courts, certifying identity and voluntary consent of all parties.',
      },
      {
        q: 'Can New Guide draft the legal contract prior to notarization?',
        a: 'Yes. Our legal translation and documentation team drafts compliant bilingual contracts meeting all statutory requirements of Dubai Courts Notary Public.',
      },
    ],
    primaryCta: 'EXPLORE NOTARY SERVICES',
    visualType: 'notary',
    image: '/service/16.png',
    statLabel: 'JUDICIAL ATTESTATION',
    statValue: 'DUBAI COURTS NOTARY',
  },
  {
    num: '17',
    id: 'emirates-id-medical',
    title: 'Emirates ID / Medical',
    headline: 'EMIRATES ID /\nMEDICAL',
    description:
      'The definitive completion journey for all UAE residency permits: VIP medical fitness test typing and expedited scheduling paired with ICP Emirates ID biometric clearances.',
    context: 'Modern UAE residency-processing journey & medical fitness',
    authority: 'ICP & DUBAI HEALTH AUTHORITY (DHA)',
    authorityFull: 'Federal Authority for Identity & Citizenship (ICP) and DHA Medical Fitness Centers',
    jurisdiction: 'FEDERAL IDENTITY & MEDICAL CENTRES',
    categoryType: 'RESIDENCY COMPLETION PROTOCOL',
    turnaround: '4-Hour VIP or 24-Hour Expedited',
    procedures: [
      'VIP Expedited Medical Fitness Test Appointments (4H/24H)',
      'Emirates ID Typing & Biometrics Scheduling',
      'Urgent Emirates ID Card Processing & Courier Dispatch',
      'Lost / Damaged Emirates ID Immediate Replacement',
      'Biometric Exemption Applications & Senior Processing',
    ],
    requiredDocuments: [
      'Applicant Original Passport with Valid Entry Permit or Visa',
      'High-Resolution Passport-Sized Photograph (white background)',
      'Sponsor Emirates ID and Establishment Card Copy',
      'Previous Emirates ID copy (if renewal or modification)',
    ],
    faqs: [
      {
        q: 'How fast can VIP medical fitness test results be issued?',
        a: 'Through our authorized Smart Salem and VIP VIP medical channels, results can be certified in as little as 30 minutes to 4 hours.',
      },
      {
        q: 'Is biometric fingerprinting required for every applicant?',
        a: 'Biometric capture is mandatory for first-time applicants aged 15 and above. For renewals where biometric records already exist in the federal system, in-person capture is usually waived.',
      },
    ],
    primaryCta: 'EXPLORE EMIRATES ID / MEDICAL',
    visualType: 'emirates-id',
    image: '/service/17.png',
    statLabel: 'IDENTITY MILESTONE',
    statValue: 'ICP & DHA CERTIFIED',
  },
];

// Helper functions for easy lookup and sequential navigation
export const getServiceById = (id) => DIRECTORY_SERVICES.find((s) => s.id === id);

export const getNextService = (currentId) => {
  const currentIndex = DIRECTORY_SERVICES.findIndex((s) => s.id === currentId);
  if (currentIndex === -1 || currentIndex === DIRECTORY_SERVICES.length - 1) {
    return DIRECTORY_SERVICES[0];
  }
  return DIRECTORY_SERVICES[currentIndex + 1];
};

export const getPrevService = (currentId) => {
  const currentIndex = DIRECTORY_SERVICES.findIndex((s) => s.id === currentId);
  if (currentIndex <= 0) {
    return DIRECTORY_SERVICES[DIRECTORY_SERVICES.length - 1];
  }
  return DIRECTORY_SERVICES[currentIndex - 1];
};

export const AUTHORITIES_LIST = [
  {
    abbr: 'MOFA',
    fullName: 'Ministry of Foreign Affairs',
    role: 'Attestation & Legalisation',
    description: 'Document authentication, embassy legalization, cross-border validity.',
  },
  {
    abbr: 'MOHRE',
    fullName: 'Ministry of Human Resources & Emiratisation',
    role: 'Labour & Employment',
    description: 'Work permits, employment quotas, establishment card registration, labour compliance.',
  },
  {
    abbr: 'ICP',
    fullName: 'Federal Authority for Identity, Citizenship & Port Security',
    role: 'Identity & Residency',
    description: 'Emirates ID processing, federal visas, entry permits, biometric appointments.',
  },
  {
    abbr: 'GDRFA',
    fullName: 'General Directorate of Residency and Foreigners Affairs',
    role: 'Dubai Immigration',
    description: 'Residency permits, Golden Visas, entry stamps, establishment files.',
  },
  {
    abbr: 'DET',
    fullName: 'Department of Economy and Tourism',
    role: 'Business Licensing',
    description: 'Mainland trade licenses, initial approvals, activity modifications, commercial registry.',
  },
  {
    abbr: 'DUBAI MUNICIPALITY',
    fullName: 'Dubai Municipality',
    role: 'Municipal Approvals',
    description: 'Layout approvals, fit-out clearances, food safety permits, environmental compliance.',
  },
  {
    abbr: 'DUBAI COURTS',
    fullName: 'Dubai Courts & Notary Public',
    role: 'Notary & POA',
    description: 'Power of Attorney notarization, sworn translations, contract attestation, legal validation.',
  },
  {
    abbr: 'UAE FREE ZONES',
    fullName: 'Economic & Special Free Zone Authorities',
    role: 'Company Formation',
    description: '100% tax-exempt entity setup across DMCC, IFZA, DAFZA, JAFZA, and 40+ zones.',
  },
];
